### ISSUE TITLE
cant set anything team related: tColor is null

### ISSUE THREAD

**Issue by ThatPotatoDev** [tomkeuper/BedWars1058#374]
### Make sure to check before creating a Bug Report

- [x] The issue isn't already found on the Issue tracker.
- [x] My issue is about **BedWars2023** and not any addon.
- [x] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

API Bug

### What happened?

https://mclo.gs/mv3OGCl

and it is there in the arena config 
```yaml
Team:
  Blue:
    Color: BLUE
    Spawn: -114.5,88.0,-1.5,-90.0,0.0
  Red:
    Color: RED
    Spawn: 115.5,88.0,-1.5,90.0,0.0
```
i've restarted multiple times since creating the teams

### Expected Behaviour

to create the holo and not error

### How to Reproduce

1. create a team
2. try to set smth team related ex. /bw setBed teamName
